### ISSUE TITLE
njoy processing issue with fendl data

### ISSUE THREAD

**Issue by shimwell** [openmc-data-storage/openmc_data#50]
Processing FENDL files with openmc and the openmc interface to NJOY raises the following errors:

openmc_data/fendl-3.2a-endf/neutron/endf/n_0131_1-H-3.endf 'utf-8' codec can't decode byte 0x92 in position 7137: invalid start byte
openmc_data/fendl-3.2a-endf/neutron/endf/n_0825_8-O-16.endf invalid literal for int() with base 10: '0         0'
openmc_data/fendl-3.2a-endf/neutron/endf/n_4843_48-Cd-112.endf invalid literal for int() with base 10: ''
openmc_data/fendl-3.2a-endf/neutron/endf/n_9228_92-U-235.endf Command 'njoy' returned non-zero exit status 2.
openmc_data/fendl-3.2-endf/neutron/endf/n_9228_92-U-235.endf Command 'njoy' returned non-zero exit status 2.
openmc_data/fendl-3.2-endf/neutron/endf/n_4843_48-Cd-112.endf invalid literal for int() with base 10: ''
openmc_data/fendl-3.2-endf/neutron/endf/n_0131_1-H-3.endf 'utf-8' codec can't decode byte 0x92 in position 7137: invalid start byte
/home/jshimwell/openmc_data/fendl-3.1d-endf/n_0131_1-H-3.txt 'utf-8' codec can't decode byte 0x92 in position 7137: invalid start byte
openmc_data/fendl-3.1d-endf/n_0628_6-C-13.txt Command 'njoy' returned non-zero exit status 77.
openmc_data/fendl-3.1d-endf/n_0831_8-O-18.txt Command 'njoy' returned non-zero exit status 77.
openmc_data/fendl-3.1d-endf/n_9228_92-U-235.txt Command 'njoy' returned non-zero exit status 2.
openmc_data/fendl-3.1a-endf/n_9228_92-U-235.txt Command 'njoy' returned non-zero exit status 2.
openmc_data/fendl-3.1a-endf/n_0831_8-O-18.txt Command 'njoy' returned non-zero exit status 77.
openmc_data/fendl-3.1a-endf/n_0628_6-C-13.txt Command 'njoy' returned non-zero exit status 77.
openmc_data/fendl-3.1a-endf/n_0131_1-H-3.txt 'utf-8' codec can't decode byte 0x92 in position 7137: invalid start byte

This can be reproduced by running these commands after installing the openmc_data package openmc and njoy
```
conda install -c conda-forge openmc njoy2016
pip install openmc_data
generate_fendl -r 3.2a
generate_fendl -r 3.2
generate_fendl -r 3.1d
generate_fendl -r 3.1a
generate_fendl -r 3.0
generate_fendl -r 3.2b
```

essentially these scripts download the fendl data then call ```openmc.data.IncidentNeutron().from_endf(filename)``` with all the endf text files and some of the files cause errrors

tagging @gschnabel for your interest

**Comment by shimwell** [comment]
/home/jshimwell/openmc_data/fendl-3.1a-endf/n_9228_92-U-235.txt Command 'njoy' returned non-zero exit status 2.

**Comment by shimwell** [comment]
/home/jshimwell/openmc_data/fendl-3.1a-endf/n_0831_8-O-18.txt Command 'njoy' returned non-zero exit status 77.

**Comment by shimwell** [comment]
/home/jshimwell/openmc_data/fendl-3.1a-endf/n_0628_6-C-13.txt Command 'njoy' returned non-zero exit status 77.

**Comment by shimwell** [comment]
/home/jshimwell/openmc_data/fendl-3.1a-endf/n_0131_1-H-3.txt 'utf-8' codec can't decode byte 0x92 in position 7137: invalid start byte

**Comment by gschnabel** [comment]
Thanks Jon for tagging me.

I can confirm that these issues are caused by wrong formatting of the FENDL ENDF-6 files. I think this issue is better placed at the [FENDL-ENDF](https://github.com/iaea-nds/fendl-endf) repo.

Would you like to open it there @shimwell?

**Comment by shimwell** [comment]
sure, I can open it there. Many thanks for visiting, see you on the other repo
